[build]
target = "x86_64-unknown-linux-musl"

# [target.'cfg(target_os = "linux")']
# rustflags += ["-C", "linker=ld.lld", "-C", "relocation-model=static", "-C", "strip=symbols"]

# [target.aarch64-unknown-linux-musl]
# rustflags += ["-C", "link-arg=/root/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/libc.a"]
# rustflags += ["-C", "-mno-outline-atomics"]
# rustflags += ["-Clinker=rust-lld"]
[target.aarch64-unknown-linux-musl]
rustflags = ["-Clinker=rust-lld",  "-Clinker-flavor=gnu-lld-cc"]
